branches:
  only:
    - master

language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_script:
  - rustup install nightly
  - rustup component add rustfmt --toolchain nightly

script:
  - cargo +nightly fmt -- --check
  - cargo build
  - cargo test -- --nocapture

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libasound2-dev
      - libjack-dev

notifications:
  webhooks:
    - secure: "hvFZVkqvLDneVNmrg1uP8zlYo063vViq6jab3UVoKUYiI1SsJND6hfrDbV2b6axs6KbjenAu8NqA+7i43Q+PjkK68irUnmMV1/JOQm8jqnZ9FGaIMLifnxBVe6mqck5o5h6ZBOxiiRAPTqFczipo2l27ZhBDvRZxaHWemwEQowrkHZmtVP/pA4s1sdhhw8fpM3lh9HvqrRXgjaUH6e+nbmYwUDt5Rijv9WCzoeiiAYs8sxKKmdpObhSeQxleyEe99Ql7Z2DnsXzY7NGvTKS2+cw/Ekl4jdysZJs5oTk3PQci4dWMFSOcrtg1AywkzPYJEMrKgZotM4HXd1kZQd6k3L0OrAj9tY9xCOQWXZzeO9ccVIoxUc6G/K3nN/HKe1Hk4fLTl6Ux7yJzeOktl/RxhFyKZzYoYdyM/YgZJX7BETAPZwCjFgDn5ogkGkaon3TIuiH4DiZ3GeJIpeDMcsegENJuh4OIysG2jY3Dmp43PBD0GrTbQtTRdUwBlrZAqBDMJ3kuG3sHXJT0NiUxC1mVBpTpbMScMiVUdenWSU2RnwPJT0G4BgqletKaU4bNNrafgFAdvCkhVgg8d7cDzZpQAhjvwdyH+H2bf3uFtxoMiJadU41ZSTpf9WwLlEWemgC13qvkR+7/yeElnyBRxYhYATsCA57/HW/w00zYDf8J0SU="
