branches:
  only:
    - master

language: rust

rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test -- --nocapture

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libasound2-dev
      - libjack-dev
